### ISSUE TITLE
Update quickstart docs & OpenAPI spec for execution api 

### ISSUE THREAD

**Issue by denopink** [suborbital/compute-feedback#6]
In https://docs.suborbital.dev/quickstart/3.-write-functions#executing-functions it's implied to use the 32 char compute token:

![image](https://user-images.githubusercontent.com/12867159/143961697-192b3b28-2e37-4517-8494-a09e70795914.png)

Where `Step 1` we created a 32 char compute token  with `subo compute create token <email>`

That led me to assume that I was suppose to use the same token for the `test api` and `execution api`.

@jagger27 and @cohix clarified that the 32 char compute token is used for the `execution api` and the 24 char editor token is used for the `test api`.  It would be great to clarify this in the https://docs.suborbital.dev/quickstart/3.-write-functions#editor-urls or at https://docs.suborbital.dev/quickstart/3.-write-functions#executing-functions

**Comment by divya-mohan0209** [comment]
[PR](https://github.com/suborbital/scn/pull/206) opened to address this issue.

**Comment by divya-mohan0209** [comment]
The [PR](https://github.com/suborbital/scn/pull/206) has been merged. Hence closing the issue.
